version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
      - npm run defaultDocument
      - npm run securityHeaders
      
  build:
    commands:
      - echo Build Phase
      - npm run build
      - npm run package
      - npm run deploy
  post_build:
    commands:
      - echo PostBuild Phase
      # - aws s3 sync ./dist $S3_BUCKET

artifacts:
  files:
    - '**/*'
  base-directory: dist
